// SPDX-FileCopyrightText: 2026 Home Energy Foundry Limited and contributors
// SPDX-License-Identifier: AGPL-3.0-only

import { describe, expect, it } from 'vitest';
import type { Element } from '../../geometry/types';
import {
  classifyPitch,
  extractSystemTypeLabelFromExtraJson,
  generateUniqueElementName,
  looksLikeAutoGeneratedName,
  normalizeAutoNameLabel,
  normalizeAutoNameTypeToken,
} from '../elementAutoNaming';

describe('elementAutoNaming', () => {
  it('normalizes convention labels while preserving known acronyms', () => {
    expect(normalizeAutoNameLabel('mvhr-high_efficiency')).toBe('MVHR High Efficiency');
    expect(normalizeAutoNameTypeToken('HeatPump')).toBe('Heat Pump');
  });

  it('extracts system names from nested extra_json type fields', () => {
    const system: Pick<Element, 'type'> & Partial<Element> = {
      type: 'System',
      subcategory: 'HeatSourceWet',
      extra_json: {
        HeatSourceWet: {
          boiler: { type: 'RegularBoiler' },
        },
      },
    };

    expect(extractSystemTypeLabelFromExtraJson(system)).toBe('Regular Boiler');
  });

  it('classifies pitch values using the existing naming bands', () => {
    expect(classifyPitch(90)).toBe('vertical');
    expect(classifyPitch(0)).toBe('horizontal-up');
    expect(classifyPitch(180)).toBe('horizontal-down');
    expect(classifyPitch(35)).toBe('up-facing-slope');
    expect(classifyPitch(120)).toBe('down-facing-slope');
  });

  it('generates unique suffixes and recognises auto-generated variants', () => {
    expect(generateUniqueElementName('Wall (S)', ['Wall (S)', 'Wall (S) 1'])).toBe('Wall (S) 2');
    expect(looksLikeAutoGeneratedName('Wall (S)', 'Wall (S)')).toBe(true);
    expect(looksLikeAutoGeneratedName('Wall (S) 3', 'Wall (S)')).toBe(true);
    expect(looksLikeAutoGeneratedName('Custom Wall (S)', 'Wall (S)')).toBe(false);
  });

  it('uses the provided formatter for positioned number tokens', () => {
    const format = (number?: string) => ['Wall', number, 'GF', '(S)'].filter(Boolean).join('-');

    expect(generateUniqueElementName('Wall-GF-(S)', ['Wall-GF-(S)', 'Wall-1-GF-(S)'], format)).toBe('Wall-2-GF-(S)');
    expect(looksLikeAutoGeneratedName('Wall-12-GF-(S)', 'Wall-GF-(S)', format)).toBe(true);
    expect(looksLikeAutoGeneratedName('Wall-GF-(S)-12', 'Wall-GF-(S)', format)).toBe(false);
  });

  it('falls back to a suffix when the formatter does not consume the number token', () => {
    const format = () => 'Thermal Bridge';

    expect(generateUniqueElementName('Thermal Bridge', ['Thermal Bridge'], format)).toBe('Thermal Bridge 1');
  });
});
