// SPDX-FileCopyrightText: 2026 Home Energy Foundry Limited and contributors
// SPDX-License-Identifier: AGPL-3.0-only

import { describe, expect, it } from 'vitest';
import type { SpaceLabel } from '../../geometry/types';
import {
  generateDefaultSpaceLabelName,
  getSpaceLabelBaseNameForRoomType,
  spaceLabelNameLooksAutoGenerated,
} from '../spaceLabelNaming';

describe('spaceLabelNaming', () => {
  it('humanizes registry slugs', () => {
    expect(getSpaceLabelBaseNameForRoomType('living_room')).toBe('Living Room');
    expect(getSpaceLabelBaseNameForRoomType('')).toBe('Space');
  });

  it('generates unique names in zone', () => {
    const a: SpaceLabel = {
      id: '1',
      name: 'Kitchen',
      zoneId: 'z',
      storey: 0,
      room_type: 'kitchen',
      coordinates: [],
    };
    expect(generateDefaultSpaceLabelName('kitchen', [a])).toBe('Kitchen 1');
    expect(generateDefaultSpaceLabelName('', [a])).toBe('Space');
  });

  it('detects auto-style names case-insensitively', () => {
    expect(spaceLabelNameLooksAutoGenerated('Living Room', 'living_room')).toBe(true);
    expect(spaceLabelNameLooksAutoGenerated('living room', 'living_room')).toBe(true);
    expect(spaceLabelNameLooksAutoGenerated('Custom wing', 'living_room')).toBe(false);
  });
});
