// SPDX-FileCopyrightText: 2026 Home Energy Foundry Limited and contributors
// SPDX-License-Identifier: AGPL-3.0-only

import type { SpaceLabel } from '../geometry/types';

function escapeRegExp(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * Human-readable base label from room_type registry slug (e.g. living_room → "Living room").
 * Empty / unknown → "Space" (then uniquified, like element default names).
 */
export function getSpaceLabelBaseNameForRoomType(roomType: string): string {
  const t = roomType.trim();
  if (!t) return 'Space';
  return t
    .split('_')
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join(' ');
}

function uniqueNameInList(base: string, existing: string[]): string {
  if (!existing.includes(base)) return base;
  let n = 1;
  let candidate = `${base} ${n}`;
  while (existing.includes(candidate)) {
    n += 1;
    candidate = `${base} ${n}`;
  }
  return candidate;
}

/** Next default name for a new or updated label in a zone, matching element `generateUniqueElementName` behaviour. */
export function generateDefaultSpaceLabelName(
  roomType: string,
  labelsInZone: SpaceLabel[],
  excludeId?: string,
): string {
  const base = getSpaceLabelBaseNameForRoomType(roomType);
  const used = labelsInZone.filter((l) => l.id !== excludeId).map((l) => l.name);
  return uniqueNameInList(base, used);
}

export function spaceLabelNameLooksAutoGenerated(name: string, roomType: string): boolean {
  const base = getSpaceLabelBaseNameForRoomType(roomType);
  if (!name.trim()) return true;
  const re = new RegExp(`^${escapeRegExp(base)}(?: \\d+)?$`, 'i');
  return re.test(name.trim());
}
