// SPDX-FileCopyrightText: 2026 Home Energy Foundry Limited and contributors
// SPDX-License-Identifier: AGPL-3.0-only

import type { SpaceLabel } from '../../geometry/types';
import { SPACE_LABEL_OPEN_TO_LIVING_ROOM_KEY } from '../spaceLabelDerivation';
import { generateDefaultSpaceLabelName, spaceLabelNameLooksAutoGenerated } from '../spaceLabelNaming';
import { signedShoelaceArea2 } from './signedArea';
import type { InferredSpaceFootprint, PlanarPoint2 } from './types';

export type RemapInferenceResult = {
  labels: SpaceLabel[];
  /** Labels matched with low confidence — `room_type` cleared per PRD (re-check). */
  roomTypesCleared: number;
};

function polygonAreaAbs(ring: PlanarPoint2[]): number {
  return Math.abs(signedShoelaceArea2(ring));
}

export function polygonCentroid2d(ring: PlanarPoint2[]): PlanarPoint2 {
  let cx = 0;
  let cy = 0;
  const n = ring.length;
  if (n === 0) return { x: 0, y: 0 };
  for (let i = 0; i < n; i++) {
    cx += ring[i].x;
    cy += ring[i].y;
  }
  return { x: cx / n, y: cy / n };
}

import { isPointInPolygon2D as pointInPolygon } from '../pointInPolygon';

export { pointInPolygon };

function labelFootprintRing(label: SpaceLabel): PlanarPoint2[] | null {
  const c = label.coordinates;
  if (!Array.isArray(c) || c.length < 3) return null;
  return c.map((p) => ({ x: p.x, y: p.y }));
}

function ringToSpaceCoords(ring: PlanarPoint2[], wallZ: number): SpaceLabel['coordinates'] {
  return ring.map((p) => ({ x: p.x, y: p.y, z: wallZ }));
}

type Scored = {
  fi: number;
  label: SpaceLabel;
  score: number;
  strong: boolean;
};

/**
 * Below this area-ratio (smaller / larger) the prior label and the new footprint are
 * treated as different rooms — no match is considered, a fresh label is generated.
 */
const MIN_AREA_RATIO_FOR_MATCH = 0.06;

/**
 * Above this area-ratio AND with mutual centroid containment, the match is "strong":
 * the prior `room_type` is preserved. Below this, the match still binds (so the user
 * does not lose their hand-placed label), but `room_type` is cleared per the PRD —
 * the room may have changed enough that the previous classification is no longer safe.
 */
const MIN_AREA_RATIO_FOR_STRONG_MATCH = 0.26;

function matchScore(label: SpaceLabel, fp: InferredSpaceFootprint): { score: number; strong: boolean } {
  const Lring = labelFootprintRing(label);
  const aF = fp.areaM2;
  if (!Lring || aF < 1e-8) return { score: 0, strong: false };
  const aL = polygonAreaAbs(Lring);
  if (aL < 1e-8) return { score: 0, strong: false };
  const ratio = Math.min(aL, aF) / Math.max(aL, aF);
  if (ratio < MIN_AREA_RATIO_FOR_MATCH) return { score: 0, strong: false };

  const cL = polygonCentroid2d(Lring);
  const cF = polygonCentroid2d(fp.ring);
  const LcentInF = pointInPolygon(cL, fp.ring);
  const FcentInL = pointInPolygon(cF, Lring);

  if (!LcentInF && !FcentInL) return { score: 0, strong: false };

  const strong = LcentInF && FcentInL && ratio >= MIN_AREA_RATIO_FOR_STRONG_MATCH;
  const score = strong ? 100 + ratio : 10 * ratio + (LcentInF ? 2 : 0) + (FcentInL ? 1 : 0);
  return { score, strong };
}

/**
 * Greedy overlap / centroid remap: stable matches keep `room_type`; weak matches clear it (PRD: prefer unassign over wrong guess).
 */
export function remapZoneSpaceLabelsFromInference(
  prevInZone: SpaceLabel[],
  footprints: InferredSpaceFootprint[],
  zoneId: string,
  newId: () => string,
  wallFingerprint?: string,
): RemapInferenceResult {
  const pairs: Scored[] = [];
  for (let fi = 0; fi < footprints.length; fi++) {
    const fp = footprints[fi];
    for (const label of prevInZone) {
      if (label.zoneId !== zoneId) continue;
      if (label.storey !== fp.storeyIndex) continue;
      const { score, strong } = matchScore(label, fp);
      if (score <= 0) continue;
      pairs.push({ fi, label, score, strong });
    }
  }
  pairs.sort((a, b) => b.score - a.score);

  const usedFace = new Set<number>();
  const usedLabel = new Set<string>();
  const built: SpaceLabel[] = [];
  let roomTypesCleared = 0;

  for (const p of pairs) {
    if (usedFace.has(p.fi) || usedLabel.has(p.label.id)) continue;
    usedFace.add(p.fi);
    usedLabel.add(p.label.id);
    const fp = footprints[p.fi];
    const coords = ringToSpaceCoords(fp.ring, fp.wallZIndex);
    const strong = p.strong;
    let room_type = p.label.room_type;
    if (!strong) {
      if (room_type) roomTypesCleared++;
      room_type = '';
    }

    const wasAutoName =
      p.label._nameAutoSync === true ||
      (p.label._nameAutoSync !== false &&
        spaceLabelNameLooksAutoGenerated(p.label.name, p.label.room_type));

    let name = p.label.name;
    let _nameAutoSync: boolean | undefined = p.label._nameAutoSync;
    if (!strong && wasAutoName) {
      name = generateDefaultSpaceLabelName(room_type, built.filter((x) => x.zoneId === zoneId), p.label.id);
      _nameAutoSync = true;
    }
    const extra_json = { ...(p.label.extra_json ?? {}) };
    if (!strong) delete extra_json[SPACE_LABEL_OPEN_TO_LIVING_ROOM_KEY];

    built.push({
      ...p.label,
      coordinates: coords,
      storey: fp.storeyIndex,
      room_type,
      name,
      _nameAutoSync,
      source: 'inferred',
      extra_json: {
        ...extra_json,
        ...(wallFingerprint ? { inference_wall_print: wallFingerprint } : {}),
        space_label_source: 'inferred',
      },
    });
  }

  for (let fi = 0; fi < footprints.length; fi++) {
    if (usedFace.has(fi)) continue;
    const fp = footprints[fi];
    const id = newId();
    const coords = ringToSpaceCoords(fp.ring, fp.wallZIndex);
    const inZone = built.filter((x) => x.zoneId === zoneId);
    built.push({
      id,
      name: generateDefaultSpaceLabelName('', inZone, id),
      zoneId,
      storey: fp.storeyIndex,
      room_type: '',
      coordinates: coords,
      source: 'inferred',
      _nameAutoSync: true,
      extra_json: {
        ...(wallFingerprint ? { inference_wall_print: wallFingerprint } : {}),
        space_label_source: 'inferred',
      },
    });
  }

  built.sort((a, b) => {
    if (a.storey !== b.storey) return a.storey - b.storey;
    const ra = a.coordinates.map((c) => ({ x: c.x, y: c.y }));
    const rb = b.coordinates.map((c) => ({ x: c.x, y: c.y }));
    const ca = polygonCentroid2d(ra);
    const cb = polygonCentroid2d(rb);
    if (ca.x !== cb.x) return ca.x - cb.x;
    return ca.y - cb.y;
  });

  return { labels: built, roomTypesCleared };
}

export function spaceLabelCoordsFingerprint(label: SpaceLabel): string {
  return label.coordinates
    .map((c) => `${c.x.toFixed(6)},${c.y.toFixed(6)},${c.z}`)
    .join('|');
}

export function labelsListContentEqual(a: SpaceLabel[], b: SpaceLabel[]): boolean {
  if (a.length !== b.length) return false;
  const aa = [...a].sort((x, y) => x.id.localeCompare(y.id));
  const bb = [...b].sort((x, y) => x.id.localeCompare(y.id));
  const byId = new Map(bb.map((x) => [x.id, x]));
  for (const x of aa) {
    const y = byId.get(x.id);
    if (!y) return false;
    if (x.room_type !== y.room_type || x.storey !== y.storey) return false;
    if (spaceLabelCoordsFingerprint(x) !== spaceLabelCoordsFingerprint(y)) return false;
  }
  return true;
}
