// SPDX-FileCopyrightText: 2026 Home Energy Foundry Limited and contributors
// SPDX-License-Identifier: AGPL-3.0-only

import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

import {
  generateCargoSbom,
  parseCargoLockPackages,
  renderCargoSbom,
} from './generate-cargo-sbom.mjs';

const firstLock = `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "workspace-package"
version = "0.1.0"

[[package]]
name = "same-package"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

[[package]]
name = "same-package"
version = "1.0.0"
source = "git+https://github.com/example/same-package?rev=abc#abcdef"
`;

const reorderedLock = `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "same-package"
version = "1.0.0"
source = "git+https://github.com/example/same-package?rev=abc#abcdef"

[[package]]
name = "workspace-package"
version = "0.1.0"

[[package]]
name = "same-package"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
`;

test('parses every non-local Cargo.lock package and excludes workspace packages', () => {
  assert.deepEqual(parseCargoLockPackages(firstLock), [
    {
      checksum: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
      name: 'same-package',
      source: 'registry+https://github.com/rust-lang/crates.io-index',
      version: '1.0.0',
    },
    {
      checksum: undefined,
      name: 'same-package',
      source: 'git+https://github.com/example/same-package?rev=abc#abcdef',
      version: '1.0.0',
    },
  ]);
});

test('renders a deterministic component for each distinct locked source', () => {
  const first = generateCargoSbom(firstLock);
  const reordered = generateCargoSbom(reorderedLock);

  assert.deepEqual(first, reordered);
  assert.equal(first.bomFormat, 'CycloneDX');
  assert.equal(first.specVersion, '1.6');
  assert.equal(first.components.length, 2);
  assert.equal(new Set(first.components.map((component) => component['bom-ref'])).size, 2);
  assert.deepEqual(
    first.components.map((component) => component.properties[0].value),
    [
      'git+https://github.com/example/same-package?rev=abc#abcdef',
      'registry+https://github.com/rust-lang/crates.io-index',
    ],
  );
  assert.deepEqual(first.components[1].hashes, [
    {
      alg: 'SHA-256',
      content: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    },
  ]);
  assert.equal(renderCargoSbom(firstLock), renderCargoSbom(reorderedLock));
});

test('covers every non-local package in the repository Cargo.lock', () => {
  const cargoLock = readFileSync(new URL('../Cargo.lock', import.meta.url), 'utf8');
  const packages = parseCargoLockPackages(cargoLock);
  const sbom = generateCargoSbom(cargoLock);

  assert.ok(packages.length > 0);
  assert.equal(sbom.components.length, packages.length);
  assert.equal(
    new Set(sbom.components.map((component) => component['bom-ref'])).size,
    packages.length,
  );
});
