// SPDX-FileCopyrightText: 2026 Home Energy Foundry Limited and contributors
// SPDX-License-Identifier: AGPL-3.0-only

export type {
  GeometryDocumentContents,
  GeometryDocumentDerivedResource,
  GeometryDocumentInput,
  GeometryDocumentKnownDerivedResourceRole,
  GeometryDocumentModel,
  GeometryDocumentPatch,
  GeometryDocumentReplacement,
  GeometryDocumentSession,
  GeometryDocumentSnapshot,
  GeometryDocumentSourceFile,
  GeometryDocumentSourceFileRole,
  GeometryDocumentSubscriber,
} from './contracts';
export { toPortableGeometryDocument } from './documentContents';
export {
  findTabularGeometryCsvStart,
  isGeometryCsvSectionHeaderLine,
  isTabularGeometryCsvSectionHeaderLine,
  KNOWN_GEOMETRY_CSV_SECTIONS,
  parseGeometryCsvLine,
} from './geometryCsvSections';
export { createInMemoryGeometryDocumentSession } from './inMemoryGeometryDocumentSession';
export {
  createSerializedGeometryDocumentHostPort,
  type GeometryDocumentHostCancelled,
  type GeometryDocumentHostCompleted,
  type GeometryDocumentHostDestructiveRequest,
  type GeometryDocumentHostDriver,
  type GeometryDocumentHostDriverSnapshot,
  type GeometryDocumentHostNewRequest,
  type GeometryDocumentHostOpenRequest,
  type GeometryDocumentHostOperation,
  type GeometryDocumentHostPort,
  type GeometryDocumentHostPreparedOperation,
  type GeometryDocumentHostResult,
  type GeometryDocumentHostSnapshot,
  type GeometryDocumentHostSuperseded,
  type GeometryDocumentHostTarget,
  type SerializedGeometryDocumentHostPortOptions,
} from './documentHostPort';
export {
  filterGeometryDocumentCatalogueEntries,
  GeometryWorkspaceProviderError,
  type GeometryDocumentCatalogueEntry,
  type GeometryDocumentCatalogueFilter,
  type GeometryDocumentCreateRequest,
  type GeometryDocumentDeleteReceipt,
  type GeometryDocumentDeleteRequest,
  type GeometryDocumentDuplicateReceipt,
  type GeometryDocumentDuplicateRequest,
  type GeometryDocumentMembershipReceipt,
  type GeometryDocumentOpenRequest,
  type GeometryDocumentPersistenceReceipt,
  type GeometryDocumentUpdateRequest,
  type GeometryProjectGroupCatalogueEntry,
  type GeometryProjectGroupCreateRequest,
  type GeometryProjectGroupDeleteReceipt,
  type GeometryProjectGroupDeleteRequest,
  type GeometryProjectGroupMutationReceipt,
  type GeometryProjectGroupSetDocumentMembershipRequest,
  type GeometryProjectGroupUpdateRequest,
  type GeometryStoredDocument,
  type GeometryWorkspaceDocumentOperations,
  type GeometryWorkspaceProjectGroupOperations,
  type GeometryWorkspaceProvider,
  type GeometryWorkspaceProviderCapabilities,
  type GeometryWorkspaceProviderErrorCode,
  type GeometryWorkspaceProviderErrorDetails,
  type GeometryWorkspaceProviderIdKind,
  type GeometryWorkspaceProviderResource,
  type GeometryWorkspaceSnapshot,
} from './providerContracts';
export {
  geometryDocumentNameKey,
  geometryProjectGroupNameKey,
  nextDuplicateGeometryDocumentName,
  normalizeGeometryDocumentName,
  normalizeGeometryProjectGroupName,
} from './documentNaming';
export {
  createInMemoryGeometryWorkspaceProvider,
  type InMemoryGeometryWorkspaceDocumentSeed,
  type InMemoryGeometryWorkspaceProjectGroupSeed,
  type InMemoryGeometryWorkspaceProviderSeed,
} from './inMemoryGeometryWorkspaceProvider';
export {
  createGeometryDocumentCoordinator,
  GeometryDocumentCoordinatorError,
  type GeometryDocumentCoordinator,
  type GeometryDocumentCoordinatorCancelled,
  type GeometryDocumentCoordinatorCompleted,
  type GeometryDocumentCoordinatorErrorCode,
  type GeometryDocumentCoordinatorOptions,
  type GeometryDocumentCoordinatorResult,
  type GeometryDocumentCoordinatorSuperseded,
  type GeometryDocumentDeleteRequest as GeometryDocumentCoordinatorDeleteRequest,
  type GeometryDocumentDirtyDecision,
  type GeometryDocumentDuplicateAndOpenRequest,
  type GeometryDocumentMembershipMutationRequest,
  type GeometryDocumentNewRequest,
  type GeometryDocumentOpenRequest as GeometryDocumentCoordinatorOpenRequest,
  type GeometryProjectGroupDeletionRequest,
} from './geometryDocumentCoordinator';
export {
  createGeometryDocumentDownload,
  GEOMETRY_CSV_MIME_TYPE,
  GeometryDocumentFileError,
  readGeometryDocumentDrop,
  readGeometryDocumentUpload,
  type GeometryDocumentDownload,
  type GeometryDocumentFileErrorCode,
} from './browserGeometryDocumentFiles';
export {
  decodePortableGeometryDocument,
  encodePortableGeometryDocument,
} from './portableDocumentCodec';
export {
  PORTABLE_GEOMETRY_DOCUMENT_EXTENSION,
  PORTABLE_GEOMETRY_DOCUMENT_FORMAT,
  PORTABLE_GEOMETRY_DOCUMENT_LIMITS,
  PORTABLE_GEOMETRY_DOCUMENT_MIME_TYPE,
  PORTABLE_GEOMETRY_DOCUMENT_VERSION,
  PortableGeometryDocumentError,
  type PortableGeometryDocument,
  type PortableGeometryDocumentDerivedResource,
  type PortableGeometryDocumentDownload,
  type PortableGeometryDocumentEncodeOptions,
  type PortableGeometryDocumentErrorCode,
  type PortableGeometryDocumentErrorDetails,
  type PortableGeometryDocumentKnownDerivedRole,
  type PortableGeometryDocumentSourceFile,
  type PortableGeometryDocumentSourceRole,
} from './portableDocumentContracts';
export {
  createPortableGeometryDocumentDownload,
  readPortableGeometryDocumentUpload,
} from './browserPortableDocumentFiles';
export {
  createBrowserPortableGeometryDocumentFileSystem,
  PortableGeometryDocumentFileSystemError,
  type PortableGeometryDocumentFileBinding,
  type PortableGeometryDocumentFileSystem,
  type PortableGeometryDocumentFileSystemCancelled,
  type PortableGeometryDocumentFileSystemCapabilities,
  type PortableGeometryDocumentFileSystemErrorCode,
  type PortableGeometryDocumentFileSystemErrorDetails,
  type PortableGeometryDocumentFileSystemOpened,
  type PortableGeometryDocumentFileSystemPermission,
  type PortableGeometryDocumentFileSystemSaved,
  type PortableGeometryDocumentFileSystemSaveOptions,
} from './browserPortableDocumentFileSystem';
export {
  IFC_IMPORT_LIMITS,
  IfcImportError,
  type IfcImportConverter,
  type IfcImportConverterRequest,
  type IfcImportConverterResult,
  type IfcImportErrorCode,
  type IfcImportErrorDetails,
  type IfcImportMode,
  type IfcImportProgress,
  type IfcImportProgressPhase,
  type IfcImportRequest,
  type IfcImportSource,
  type LocalIfcImportAdapter,
  type LocalIfcImportAdapterOptions,
} from './ifcImportContracts';
export { createLocalIfcImportAdapter } from './localIfcImportAdapter';
export {
  BROWSER_DIRECTORY_WORKSPACE_METADATA_FORMAT,
  BROWSER_DIRECTORY_WORKSPACE_METADATA_LIMITS,
  BROWSER_DIRECTORY_WORKSPACE_METADATA_VERSION,
  BrowserDirectoryWorkspaceMetadataError,
  decodeBrowserDirectoryWorkspaceMetadata,
  encodeBrowserDirectoryWorkspaceMetadata,
  type BrowserDirectoryWorkspaceArchiveDescriptor,
  type BrowserDirectoryWorkspaceDocumentRow,
  type BrowserDirectoryWorkspaceMetadata,
  type BrowserDirectoryWorkspaceMetadataErrorCode,
  type BrowserDirectoryWorkspaceMetadataErrorDetails,
  type BrowserDirectoryWorkspaceProjectGroupRow,
  type BrowserDirectoryWorkspaceSourceFileDescriptor,
} from './browserDirectoryWorkspaceMetadata';
export {
  BrowserDirectoryWorkspaceError,
  type BrowserDirectoryWorkspaceAccess,
  type BrowserDirectoryWorkspaceAccessOptions,
  type BrowserDirectoryWorkspaceBinding,
  type BrowserDirectoryWorkspaceCancelled,
  type BrowserDirectoryWorkspaceCapabilities,
  type BrowserDirectoryWorkspaceChooseResult,
  type BrowserDirectoryWorkspaceConnected,
  type BrowserDirectoryWorkspaceCreateId,
  type BrowserDirectoryWorkspaceCreateIdKind,
  type BrowserDirectoryWorkspaceErrorCode,
  type BrowserDirectoryWorkspaceErrorDetails,
  type BrowserDirectoryWorkspaceHandleStore,
  type BrowserDirectoryWorkspaceNotRemembered,
  type BrowserDirectoryWorkspacePermissionRequired,
  type BrowserDirectoryWorkspaceResourceAccess,
  type BrowserDirectoryWorkspaceResourceEntry,
  type BrowserDirectoryWorkspaceResourceListOptions,
  type BrowserDirectoryWorkspaceRestoreResult,
} from './browserDirectoryWorkspaceContracts';
export { createBrowserDirectoryWorkspaceAccess } from './browserDirectoryWorkspaceAccess';
export { createBrowserDirectoryWorkspaceResourceAccess } from './browserDirectoryWorkspaceResources';
export { createIndexedDbBrowserDirectoryWorkspaceHandleStore } from './indexedDbDirectoryWorkspaceHandleStore';
export {
  createCommunityGeometryFilesController,
  CommunityGeometryFilesControllerError,
  type CommunityGeometryDocumentReference,
  type CommunityGeometryFilesActiveConflict,
  type CommunityGeometryFilesCancelled,
  type CommunityGeometryFilesCompleted,
  type CommunityGeometryFilesController,
  type CommunityGeometryFilesControllerErrorCode,
  type CommunityGeometryFilesControllerOptions,
  type CommunityGeometryFilesDirtyOptions,
  type CommunityGeometryFilesOperation,
  type CommunityGeometryFilesResult,
  type CommunityGeometryFilesSnapshot,
  type CommunityGeometryFilesSuperseded,
  type CommunityGeometryFilesVisibleError,
  type CommunityGeometryFilesVisibleErrorSource,
  type CommunityGeometryFilesWorkspace,
  type CommunityGeometryProjectReference,
} from './communityGeometryFilesController';
